### PR TITLE
Update send-helper.md

### LINKED ISSUE #33: Add carbon copy to list of send helper for sails-mail

### PR DESCRIPTION
**Pull request by lennyAiko**
This fixes #33

### CODE REVIEW

**Comment by DominusKelvin** [comment]
Great PR. I'll merge soon. Thanks @lennyAiko

**Review by DominusKelvin — CHANGES_REQUESTED** [review]
Awesome. Thanks I definitely forgot to document this. Can you change list of names to list or email addresses?

**Comment by lennyAiko** [comment]
Sorry for the late response @DominusKelvin 

I have made the changes you requested, I also added something new as I just made use of it.

Thanks.

**Review by DominusKelvin — APPROVED** [review]
Thanks @lennyAiko

**Pull request merged**
