### PR TITLE
[chore] add google provider documentation for wish.

### PR DESCRIPTION
**Pull request by poriacodes**
Fixes issue #6 

The docs for setting up google provider in wish has been added. 

Kindly review. 

Thank you.

### CODE REVIEW

**Review by DominusKelvin — CHANGES_REQUESTED** [review]
Nice job @poriacodes it seems you may have copied bot the docs for GitHub OAuth flow and that of Google OAuth as well from the README

**Comment by poriacodes** [comment]
> Nice job @poriacodes it seems you may have copied bot the docs for GitHub OAuth flow and that of Google OAuth as well from the README

Thank you. I have fixed it now.

**Review by DominusKelvin — CHANGES_REQUESTED** [review]
Hey great job. I see you are still using the code for GitHub

**Review by DominusKelvin — APPROVED** [review]
Much better. Great job @poriacodes

**Pull request merged**
